# Generated by Django 5.2.5 on 2025-08-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficina',
            options={'verbose_name': 'oficina', 'verbose_name_plural': 'oficinas'},
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la oficina'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nombre_corto',
            field=models.SlugField(help_text='Identificador unico de la oficina', max_length=10, unique=True, verbose_name='id corto'),
        ),
    ]
